default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root_password
  host: localhost
  port: 3306

development:
  <<: *default
  database: development_database

test:
  <<: *default
  database: test_database
